### ISSUE TITLE
Read doesn't work on my machine

### ISSUE THREAD

**Issue by gabskoro** [mudbugmedia/critical-path-css-rails#14] opened 2016-11-18 12:58 UTC
Hi,

So, after I enabled the cache on my development by adding this line

```ruby
config.action_controller.perform_caching = true
```

I went to my application.slim and added the following

```slim
style
  = CriticalPathCss.fetch(request.path)

javascript:
  loadCSS("#{stylesheet_path('application')}");
```

After this, I run the server and called `bundle exec rake critical_path_css:generate` to write it to the cache.

After the page reloaded nothing happened, so I inspected the cache `Rails.cache` and saw that there is one entry but by calling `Rails.cache.read('/', namespace: 'critical-path-css')` I got an empty string. 

Do you maybe have any maybe what would go wrong?

**Comment by michael-misshore** [comment] 2017-01-18 04:45
I just tried to replicate this, and I was unable to. 

Are you getting any errors when you run `bundle exec rake critical_path_css:generate` or `bundle exec rake assets:precompile`?

**Comment by frozenfung** [comment] 2017-02-26 05:31
I have the exactly the same situation with my project. Neither `bundle exec rake critical_path_css:generate` or `bundle exec rake assets:precompile` show any errors. 

Even if I tried some low-level API like `CssFetcher.fetch` but redis returns an empty string still.

Any good advise for debugging?

**Comment by michael-misshore** [comment] 2017-03-01 18:56
What does your `config/critical_path_css.yml` file look like? Are there any routes defined? Do you have a rails server running while you're running the rake tasks? If you have a rails server running and routes defined in the `.yml`, you should be able to see the rake tasks initiating a page view for each route. I'm just trying to eliminate the easy things before diving deeper.

With that being said, I haven't tested on rails 5 yet. That's something I can check out on my end.

**Comment by frozenfung** [comment] 2017-03-02 15:03
After some work I found that it might be caused by the outdated version of phantomjs. Eventually, my problem was solved when upgrading phantomJS to `2.1.1`.

**Comment by michael-misshore** [comment] 2017-03-02 15:13
Thank you for your contribution! I'll try to get this merged in ASAP.

**Comment by michael-misshore** [comment] 2017-03-04 02:02
PR #17 corrects this issue.

**Closed by michael-misshore** 2017-03-04 02:02 UTC
