### ISSUE TITLE
Precompile not using hashed filedname and gem using different directory

### ISSUE THREAD

**Issue by mattymess** [mudbugmedia/critical-path-css-rails#10] opened 2016-09-19 23:38 UTC
When I run `rake assets:precompile`, I get the following error.

````
Unable to open file '/Users/matt/work/fanbread/repos/toaster/public/stylesheets/assets/theme_templates/v3/application.css'
````

My CSS compiles to `/Users/matt/work/fanbread/repos/toaster/public/assets/theme_templates/v3/application.css` (no stylesheets directory) and the filename has a hash appended to it.

![image](https://cloud.githubusercontent.com/assets/1108825/18652093/54435b2c-7e84-11e6-8197-5685cc5d78ad.png)

`critical_path_css.yml` is configured as... `manifest_name: assets/theme_templates/v3/application`

Any ideas? Thanks

**Comment by michael-misshore** [comment] 2016-09-19 23:57
After taking a very quick look, I think the issue is that the manifest path is currently not configurable:

https://github.com/mudbugmedia/critical-path-css-rails/blob/a721db28927ccc3ad987e1819f7abd3044520928/lib/critical_path_css/configuration.rb#L36

Out of curiosity, do you use a `stylesheet_path` helper to load the CSS in your layout? If so, what does that line of code look like.

Regardless, I think the solution here is to allow the `manifest_path` to be set in the .yml file.

**Comment by mattymess** [comment] 2016-09-20 17:21
We're using `stylesheet_link_tag`.

`= stylesheet_link_tag    'theme_templates/v3/application', media: 'all'`

Is the fact that the gem isn't looking for the hashed version of the file related?

**Comment by michael-misshore** [comment] 2016-10-04 23:22
@mattymess, sorry for the delay. I just gave this a test and here's what works for me:

```ruby
# Assets Precompile
Rails.application.config.assets.precompile += %w( theme_templates/v3/application.css )

# Manifest Name
manifest_name: theme_templates/v3/application
```

```
# Files in /public
ls -lah public/assets/theme_templates/v3/total 72K
drwxrwxr-x 4 501 dialout  136 Oct  4 18:17 .
drwxrwxr-x 3 501 dialout  102 Oct  4 18:17 ..
-rw-rw-r-- 1 501 dialout  51K Oct  4 18:15 application-7a797a86bd5038a7126470b50c5b08b983a072a260d949a19a7bd41287cd92fc.css
-rw-rw-r-- 1 501 dialout 9.6K Oct  4 18:15 application-7a797a86bd5038a7126470b50c5b08b983a072a260d949a19a7bd41287cd92fc.css.gz
```

Let me know if there's anything I'm missing with my setup.

**Comment by michael-misshore** [comment] 2016-10-06 19:11
I'll close this issue for now.

**Closed by michael-misshore** 2016-10-06 19:11 UTC

**Comment by mattymess** [comment] 2016-10-06 19:15
Hey Michael. Shouldn't there be another file in public that contains the critical CSS?

**Comment by michael-misshore** [comment] 2016-10-06 19:37
@mattymess, when you run `rake critical_path_css:generate` after `rake assets:precompile`, the critical CSS is inserted into a cache entry. The gem doesn't output the critical CSS to a file as we would not be able to take advantage of the speed benefits. The gem currently stores this in a cache entry, and may be retrieved like so (a more detailed example may be had in the Readme):

```HTML+ERB
<style>
  <%= CriticalPathCss.fetch(request.path) %>
</style>
```

Let me know if I misunderstood your question.
