### ISSUE TITLE
PhantomJs requires flags for HTTPS sites

### ISSUE THREAD

**Issue by bartboy011** [mudbugmedia/critical-path-css-rails#15] opened 2016-12-02 18:13 UTC
Hey there,

I tried implementing this gem, but my site uses ssl encryption and PhantomJs requires the following flags to handle ssl sites (courtesy of Penthouse):

```
to run on HTTPS sites two flags must be passed in, directly after phantomjs in the call:
    --ignore-ssl-errors=true --ssl-protocol=tlsv1
```

I've tried digging through the PhantomJs gem but can't seem to find a solution for this, any thoughts?

**Comment by bartboy011** [comment] 2016-12-02 18:19
Little more detail on this, here's the error that's thrown:

```
Error opening url 'https://www.example.com/': SSL handshake failed
```

**Comment by michael-misshore** [comment] 2017-01-18 04:09
I've added the recommended flags for PhantomJS via #16. I'll close this issue for now, but please feel free to reopen if the problem persists.

**Comment by darmenise** [comment] 2017-01-18 09:45
The problem persists on Heroku:

```
remote: -----> Preparing app for Rails asset pipeline[K
remote:        Running: rake assets:precompile[K
remote:        Phantomjs does not appear to be installed in /app/.phantomjs/1.9.8/x86_64-linux/bin/phantomjs, installing![K
remote:        % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current[K
remote:        Dload  Upload   Total   Spent    Left  Speed[K
remote:        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[K
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[K
remote:        19 12.5M   19 2539k    0     0  14.7M      0 --:--:-- --:--:-- --:--:-- 14.7M[K
remote: 100 12.5M  100 12.5M    0     0  42.7M      0 --:--:-- --:--:-- --:--:-- 80.5M[K
remote:        Successfully installed phantomjs. Yay![K
remote:        Removed temporarily downloaded files.[K
remote:        Error opening url 'https://example.com/': SSL handshake failed[K
remote:        Asset precompilation completed (8.04s)[K
```

It would be really nice to have it fixed because there is still no reliable way to activate `mod_pagespeed` on heroku!

**Comment by michael-misshore** [comment] 2017-01-18 13:39
@darmenise , I just tried this on one of our Heroic instances, and here are my results:

```remote:        Phantomjs does not appear to be installed in /app/.phantomjs/1.9.8/x86_64-linux/bin/phantomjs, installing!
remote:        % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:        Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
remote:        100 12.5M  100 12.5M    0     0  32.7M      0 --:--:-- --:--:-- --:--:-- 32.7M
remote:        Successfully installed phantomjs. Yay!
remote:        Removed temporarily downloaded files.
remote:        Cache write: critical-path-css:/ ({:namespace=>"critical-path-css", :expires_in=>nil})
remote:        Dalli::Server#connect XXXXXXX.com:11211
remote:        Dalli/SASL authenticating as 6a59e1
remote:        Dalli/SASL: 6a59e1
remote:        Asset precompilation completed (7.07s)```

In my `critical_path_css.yml`, I'm using a `base_url` with a known working SSL certificate. Are you using the most up to date version of this gem, `0.3.1`?

One thing I still need to do is update PhantomJS, but barring that, I'm currently unable to replicate the SSL handshake issue.

**Comment by darmenise** [comment] 2017-01-18 13:53
I'm using the edge version actually. I'm also using a custom domain and Cloudflare, maybe something goes wrong there... But the SSL certificate is definitely working: 
![screenshot 2017-01-18 14 52 23](https://cloud.githubusercontent.com/assets/794154/22066589/e64af0c6-dd8d-11e6-9daf-bab79e523475.png)


If you want I could privately give you more details.

**Comment by darmenise** [comment] 2017-01-18 14:19
Update: if I don't use the custom domain the SSL handshake is successful.
In other words if i put `https://appname.herokuapp.com` as `base_url` for production it works.
Maybe the problem is in some Cloudflare configuration..

**Comment by bartboy011** [comment] 2017-01-18 14:21
Just tried your fix @darmenise and it worked for me as well. My company uses GoDaddy for our domain names, so maybe it's something to do with Heroku's SSL implementation. Regardless, using the base Heroku url seems to fix the issue!

**Comment by bartboy011** [comment] 2017-01-18 14:24
That being said, I'm fine with the issue being closed if you're happy with the solution @michael-misshore

**Comment by darmenise** [comment] 2017-01-18 14:34
I'm glad to know that :-)

I'm still in trouble because my app uses subdomains and so I can't use that fix but it would be for another issue. This one I think it could be closed too.

**Comment by michael-misshore** [comment] 2017-01-18 15:11
Closed!

**Closed by michael-misshore** 2017-01-18 15:11 UTC
